title: Jaeseon Song
logo: /assets/Images/profile.png

description: I explore human vision and audition through psychophysics and fMRI. My study is driven by a quest to understand how we perceive and interpret the world. 
email: jaeseon@udel.edu
show_downloads: False
theme: jekyll-theme-Minimal
