title: Jaeseon Song
logo: C:/Users/Jaeseon/Documents/GitHub/JaeseonSong.github.io/profile.jpg
email: jaeseon.song at uga dot edu
description: As a Ph.D. candidate in visual perception, I explore human vision through psychophysics. My study is driven by a quest to understand how we perceive and interpret the world. Outside the lab, I pursue CrossFit, challenging both body and mind. Travel is also a passion, broadening my perspectives and enriching my personal and professional growth.
show_downloads: False
theme: jekyll-theme-Minimal

sidebar:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/JaeseonSong
