

author:
  name   : "Jaeseon Song"
  avatar : "/assets/Images/profile.jpg"
  bio    : >-
    My name is Jaeseon Song.
    As a Ph.D. candidate in visual perception, I explore human vision through psychophysics. 
    My study is driven by a quest to understand how we perceive and interpret the world. 

    I was born in Cheongju, South korea but I've been living in Athens, US since 2017.
    Outside the lab, I pursue CrossFit, challenging both body and mind. 
    Travel is also a passion, broadening my perspectives and enriching my personal and professional growth.

  location: "Athens, United States"
  linkedin: "jaeseon-song"
  github: "JaeseonSong"
  stackoverflow: "82540"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:jaeseon.song@uga.edu"
    - label: "CV"
      icon: "far fa-fw fa-file-pdf"
      url: "/assets/files/CV_JS_2023.pdf"
