title: Jaeseon Song
logo: /assets/Images/profile.png

description: As a Ph.D. candidate in visual perception, I explore human vision through psychophysics. My study is driven by a quest to understand how we perceive and interpret the world. 
email: jaeseon.song@uga.edu
show_downloads: False
theme: jekyll-theme-Minimal
